In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [3]:
df = pd.read_csv("ido_tdo_chemdist_dataset.csv", index_col=0)
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-14.003065,-23.058441,46.137160,-7.526415,-14.680629,-2.025073,-2.668684,-4.798969,16.956556,28.177288,15.778368,-7.974331,4.787653,-21.960740,3.326011,-9.688106
1,-8.993788,-30.842980,37.763935,-12.150796,-4.559561,3.368797,-16.726458,-0.450463,19.561825,22.228985,12.471409,-5.286638,14.282381,-17.962238,0.858942,-2.176952
2,-13.749965,-23.094172,46.291720,-7.666314,-14.803009,-1.674854,-2.428345,-4.950026,17.406736,28.317436,15.914805,-8.123228,4.782705,-22.040120,3.003066,-9.793180
3,-14.343452,-20.237873,46.551860,-10.752590,-14.618931,-0.115160,-1.749531,-9.018958,15.462461,29.991219,15.747241,-7.880230,3.059953,-19.909452,2.336827,-10.616964
4,-14.600085,-24.964235,47.840824,-9.838120,-15.556587,-2.510412,-6.130763,-6.216830,17.894226,29.233135,18.129982,-9.611552,4.620627,-22.341133,4.051117,-10.847528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,-6.610067,-35.240223,37.347210,-13.406092,-0.086639,4.950376,-19.595678,-1.106861,22.324460,20.796188,9.676053,-6.745124,19.218573,-20.109446,-0.283282,-3.565793
756,-10.378180,-32.026630,39.730270,-14.188325,-2.722742,2.572641,-18.544514,-3.594114,18.125656,23.397170,11.112873,-6.274046,15.503289,-18.983067,2.022580,-4.658357
757,-9.414690,-32.008568,38.020410,-12.887679,-4.310641,2.123005,-19.301645,-0.908163,19.287104,22.181587,13.006796,-6.244154,14.596760,-18.429844,2.206953,-3.002437
758,-14.033400,-24.151228,44.509490,-13.630947,-13.172363,-5.050177,-13.606611,-10.461112,14.584917,28.205460,18.197668,-12.246285,3.934439,-20.749884,8.149105,-13.534802
759,-13.990807,-23.040163,45.888317,-7.266840,-14.698127,-2.185727,-2.705161,-4.473226,16.865458,27.957777,15.767321,-7.879742,4.768635,-21.911133,3.425968,-9.508499

In [4]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [5]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [6]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, stratify=y, random_state=42)

In [8]:
clf = SVC(probability=True,kernel='rbf', random_state=42)

In [9]:
# Fit the model on the scaled training data
clf.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [10]:
# Predict on the testing set
y_pred = clf.predict(X_test)

In [12]:
print("SVM chemdist")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

SVM chemdist
              precision    recall  f1-score   support

          AA       0.51      0.60      0.55        42
          AI       0.87      0.59      0.70        34
          IA       0.00      0.00      0.00        16
          II       0.59      0.78      0.67        60

    accuracy                           0.61       152
   macro avg       0.49      0.49      0.48       152
weighted avg       0.57      0.61      0.57       152

[[25  2  0 15]
 [ 5 20  0  9]
 [ 7  0  0  9]
 [12  1  0 47]]

/run/media/rafe/volume D/Documents/new_chminformatic_project2/cheminformatic_project_1_venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/run/media/rafe/volume D/Documents/new_chminformatic_project2/cheminformatic_project_1_venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/run/media/rafe/volume D/Documents/new_chminformatic_project2/cheminformatic_project_1_venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

np.float64(0.8047772233893559)

In [13]:
clf = SVC(probability=True,kernel='linear', random_state=42)

In [14]:
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [15]:
# Predict on the testing set
y_pred = clf.predict(X_test)

In [16]:
print("SVM chemdist kernel linear")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

SVM chemdist kernel linear
              precision    recall  f1-score   support

          AA       0.49      0.67      0.57        42
          AI       0.68      0.38      0.49        34
          IA       0.00      0.00      0.00        16
          II       0.46      0.58      0.51        60

    accuracy                           0.50       152
   macro avg       0.41      0.41      0.39       152
weighted avg       0.47      0.50      0.47       152

[[28  1  0 13]
 [ 5 13  0 16]
 [ 4  0  0 12]
 [20  5  0 35]]

/run/media/rafe/volume D/Documents/new_chminformatic_project2/cheminformatic_project_1_venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/run/media/rafe/volume D/Documents/new_chminformatic_project2/cheminformatic_project_1_venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/run/media/rafe/volume D/Documents/new_chminformatic_project2/cheminformatic_project_1_venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

np.float64(0.6968621129007158)

In [17]:
clf = SVC(probability=True,kernel='rbf', random_state=42 , class_weight='balanced')

In [18]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', probability=True, random_state=42)

In [19]:
# Predict on the testing set
y_pred = clf.predict(X_test)

In [21]:
print("SVM chemdist kernel rbf balanced")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

SVM chemdist kernel rbf balanced
              precision    recall  f1-score   support

          AA       0.61      0.67      0.64        42
          AI       0.77      0.68      0.72        34
          IA       0.28      0.69      0.40        16
          II       0.76      0.47      0.58        60

    accuracy                           0.59       152
   macro avg       0.60      0.62      0.58       152
weighted avg       0.67      0.59      0.61       152

[[28  2  9  3]
 [ 5 23  2  4]
 [ 3  0 11  2]
 [10  5 17 28]]

np.float64(0.8188703606442577)

In [22]:
clf = SVC(probability=True,kernel='linear', random_state=42 , class_weight='balanced')

In [32]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear', probability=True, random_state=42)

In [33]:
# Predict on the testing set
y_pred = clf.predict(X_test)

In [34]:
print("SVM chemdist kernel linear balanced")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

SVM chemdist kernel linear balanced
              precision    recall  f1-score   support

          AA       0.46      0.79      0.58        42
          AI       0.56      0.53      0.55        34
          IA       0.32      0.56      0.41        16
          II       0.52      0.18      0.27        60

    accuracy                           0.47       152
   macro avg       0.47      0.52      0.45       152
weighted avg       0.49      0.47      0.43       152

[[33  1  6  2]
 [ 6 18  3  7]
 [ 5  1  9  1]
 [27 12 10 11]]

np.float64(0.6894719693432929)