In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('final_total', sep=' ', na_values=['na'])
df

,CHEMBLID,smiles,ido_ic50,tdo_ic50
0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,23.0,60.0
1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,10000.0,10000.0
2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,183.0,224200.0
3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,11790.0,12250.0
4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,14610.0,30230.0
...,...,...,...,...
800,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,1230.0,11240.0
801,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,56450.0,7450.0
802,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,10000.0,450.0
803,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,50.0,10000.0
804,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,53.9,53.0

In [3]:
df2 = df.dropna(ignore_index=True)
df2

,CHEMBLID,smiles,ido_ic50,tdo_ic50
0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,23.0,60.0
1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,10000.0,10000.0
2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,183.0,224200.0
3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,11790.0,12250.0
4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,14610.0,30230.0
...,...,...,...,...
755,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,1230.0,11240.0
756,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,56450.0,7450.0
757,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,10000.0,450.0
758,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,50.0,10000.0
759,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,53.9,53.0

In [4]:
df2.loc[:, 'ido_ic50'] = (np.log10((df2.loc[:, 'ido_ic50'])*10**(-9)))*(-1)

In [5]:
df2.loc[:, 'tdo_ic50'] = (np.log10((df2.loc[:, 'tdo_ic50'])*10**(-9)))*(-1)

In [6]:
df2

,CHEMBLID,smiles,ido_ic50,tdo_ic50
0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,7.638272,7.221849
1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,5.000000,5.000000
2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,6.737549,3.649364
3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,4.928486,4.911864
4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,4.835350,4.519562
...,...,...,...,...
755,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,5.910095,4.949234
756,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,4.248336,5.127844
757,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,5.000000,6.346787
758,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,7.301030,5.000000
759,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,7.268411,7.275724

In [7]:
df3 = df2.loc[:, ['ido_ic50', 'tdo_ic50']]
df3

     ido_ic50  tdo_ic50
0    7.638272  7.221849
1    5.000000  5.000000
2    6.737549  3.649364
3    4.928486  4.911864
4    4.835350  4.519562
..        ...       ...
755  5.910095  4.949234
756  4.248336  5.127844
757  5.000000  6.346787
758  7.301030  5.000000
759  7.268411  7.275724

[760 rows x 2 columns]

In [9]:
for i in range(760):
    if df3['ido_ic50'].values[i] >= 6.15:
        df3['ido_ic50'][i] = 'A'
    else:
        df3['ido_ic50'][i] = 'I'

/tmp/ipykernel_1194/3774618061.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df3['ido_ic50'][i] = 'A'
/tmp/ipykernel_1194/3774618061.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df3['ido_ic50'][i] = 'A'

In [10]:
for i in range(760):
    if df3['tdo_ic50'].values[i] >= 6.0:
        df3['tdo_ic50'][i] = 'A'
    else:
        df3['tdo_ic50'][i] = 'I'

/tmp/ipykernel_1194/565967957.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df3['tdo_ic50'][i] = 'A'
/tmp/ipykernel_1194/565967957.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['tdo_ic50'][i] = 'A'
/tmp/ipykernel_1194/565967957.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df3['tdo_ic50'][i] = 'A'

In [11]:
df3

    ido_ic50 tdo_ic50
0          A        A
1          I        I
2          A        I
3          I        I
4          I        I
..       ...      ...
755        I        I
756        I        I
757        I        A
758        A        I
759        A        A

[760 rows x 2 columns]

In [12]:
newcol = []
for i in range(760):
    if df3['ido_ic50'].values[i] == 'A' and df3['tdo_ic50'].values[i] == 'A':
        newcol.append('AA')
    elif df3['ido_ic50'].values[i] == 'I' and df3['tdo_ic50'].values[i] == 'I':
        newcol.append('II')
    elif df3['ido_ic50'].values[i] == 'I' and df3['tdo_ic50'].values[i] == 'A':
        newcol.append('IA')
    else:
        newcol.append('AI')

In [13]:
ido_tdo = pd.DataFrame(data=newcol, columns=['ido_tdo'])
ido_tdo

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [15]:
ido_tdo.to_csv(path_or_buf="ido_tdo.csv")