In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [3]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [4]:
df = pd.read_csv("chemberta_idotdo_MTR.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.098624,0.042223,-0.195243,0.209923,0.247522,-0.200116,0.130730,-0.078926,0.217784,-0.182055,...,-0.083785,-0.015257,0.208670,-0.099257,0.036652,0.011307,-0.015858,-0.034473,0.080340,0.090633
1,-0.195444,-0.006335,-0.125551,0.019175,-0.001245,-0.109488,0.118288,-0.345516,0.020197,-0.318505,...,0.153339,-0.094293,0.072913,-0.126550,0.012802,-0.071275,0.245102,-0.169543,-0.080592,-0.355988
2,0.019954,0.011441,-0.158951,0.221017,0.246666,-0.214977,0.122784,-0.182540,0.290653,-0.235725,...,-0.117349,-0.072634,0.212387,0.004530,-0.039211,-0.015519,0.015888,-0.153794,0.055760,0.118594
3,0.208809,0.168003,-0.015691,-0.009882,0.152641,0.031507,-0.038857,-0.054616,0.173442,-0.060251,...,-0.128801,-0.175998,0.109642,-0.068736,0.190212,-0.180588,0.214342,-0.124051,-0.300908,-0.076737
4,-0.041897,-0.128232,-0.096629,-0.068780,0.078374,-0.041795,0.128524,0.017905,0.171965,-0.143606,...,0.128640,-0.195388,0.355525,-0.314848,0.265437,-0.197671,0.041610,0.207000,-0.186747,0.126672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,-0.099143,0.104436,0.011019,-0.165326,0.135885,-0.002735,-0.053308,0.116025,0.044211,-0.000038,...,-0.215827,0.197586,0.226231,-0.037536,0.056611,-0.155834,-0.153475,0.095045,-0.010944,-0.130073
756,0.011156,0.046114,0.019320,0.022109,0.234958,0.037306,0.037335,0.020181,0.005356,-0.084363,...,-0.043167,0.147757,0.299443,0.175839,-0.089705,-0.102291,-0.110185,0.237602,0.147709,-0.066069
757,-0.224795,0.074084,-0.111290,-0.070322,0.037394,-0.100532,0.073335,-0.244298,0.019439,-0.383307,...,0.119012,-0.095294,0.093073,-0.222050,0.105182,-0.022975,0.171083,-0.198204,-0.140231,-0.261504
758,-0.104002,0.089321,-0.083992,0.218112,0.071453,-0.035407,0.231394,-0.124874,-0.125678,0.000591,...,0.142494,0.000984,0.231777,0.024092,0.036001,0.095570,-0.203001,-0.023051,0.020927,-0.080840
759,0.067812,-0.030397,-0.156415,0.200837,0.227610,-0.212452,0.127864,-0.159986,0.242586,-0.216630,...,-0.167850,-0.079812,0.180793,-0.038872,-0.023832,0.018703,-0.038679,-0.135613,0.073865,0.017983

In [5]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [6]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [7]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.098624,0.042223,-0.195243,0.209923,0.247522,-0.200116,0.130730,-0.078926,0.217784,-0.182055,...,-0.083785,-0.015257,0.208670,-0.099257,0.036652,0.011307,-0.015858,-0.034473,0.080340,0.090633
1,-0.195444,-0.006335,-0.125551,0.019175,-0.001245,-0.109488,0.118288,-0.345516,0.020197,-0.318505,...,0.153339,-0.094293,0.072913,-0.126550,0.012802,-0.071275,0.245102,-0.169543,-0.080592,-0.355988
2,0.019954,0.011441,-0.158951,0.221017,0.246666,-0.214977,0.122784,-0.182540,0.290653,-0.235725,...,-0.117349,-0.072634,0.212387,0.004530,-0.039211,-0.015519,0.015888,-0.153794,0.055760,0.118594
3,0.208809,0.168003,-0.015691,-0.009882,0.152641,0.031507,-0.038857,-0.054616,0.173442,-0.060251,...,-0.128801,-0.175998,0.109642,-0.068736,0.190212,-0.180588,0.214342,-0.124051,-0.300908,-0.076737
4,-0.041897,-0.128232,-0.096629,-0.068780,0.078374,-0.041795,0.128524,0.017905,0.171965,-0.143606,...,0.128640,-0.195388,0.355525,-0.314848,0.265437,-0.197671,0.041610,0.207000,-0.186747,0.126672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,-0.099143,0.104436,0.011019,-0.165326,0.135885,-0.002735,-0.053308,0.116025,0.044211,-0.000038,...,-0.215827,0.197586,0.226231,-0.037536,0.056611,-0.155834,-0.153475,0.095045,-0.010944,-0.130073
756,0.011156,0.046114,0.019320,0.022109,0.234958,0.037306,0.037335,0.020181,0.005356,-0.084363,...,-0.043167,0.147757,0.299443,0.175839,-0.089705,-0.102291,-0.110185,0.237602,0.147709,-0.066069
757,-0.224795,0.074084,-0.111290,-0.070322,0.037394,-0.100532,0.073335,-0.244298,0.019439,-0.383307,...,0.119012,-0.095294,0.093073,-0.222050,0.105182,-0.022975,0.171083,-0.198204,-0.140231,-0.261504
758,-0.104002,0.089321,-0.083992,0.218112,0.071453,-0.035407,0.231394,-0.124874,-0.125678,0.000591,...,0.142494,0.000984,0.231777,0.024092,0.036001,0.095570,-0.203001,-0.023051,0.020927,-0.080840
759,0.067812,-0.030397,-0.156415,0.200837,0.227610,-0.212452,0.127864,-0.159986,0.242586,-0.216630,...,-0.167850,-0.079812,0.180793,-0.038872,-0.023832,0.018703,-0.038679,-0.135613,0.073865,0.017983

In [8]:
X_scaled = StandardScaler().fit_transform(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [10]:
# using default values

clf = KNeighborsClassifier()

In [11]:
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [12]:
ypred = clf.predict(X_test)

In [15]:
print("knn chemberta mtr")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred) , roc_auc())

knn chemberta mtr
              precision    recall  f1-score   support

          AA       0.53      0.76      0.63        42
          AI       0.82      0.68      0.74        34
          IA       0.50      0.25      0.33        16
          II       0.77      0.72      0.74        60

    accuracy                           0.67       152
   macro avg       0.66      0.60      0.61       152
weighted avg       0.69      0.67      0.67       152

[[32  5  1  4]
 [ 7 23  0  4]
 [ 7  0  4  5]
 [14  0  3 43]] 0.8663690476190476

In [16]:
# using default values

clf = KNeighborsClassifier(weights='distance')

In [17]:
clf.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [18]:
ypred = clf.predict(X_test)

In [19]:
print("knn chemberta mtr weight = distance")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred) , roc_auc())

knn chemberta mtr weight = distance
              precision    recall  f1-score   support

          AA       0.54      0.67      0.60        42
          AI       0.74      0.68      0.71        34
          IA       0.18      0.12      0.15        16
          II       0.76      0.73      0.75        60

    accuracy                           0.64       152
   macro avg       0.56      0.55      0.55       152
weighted avg       0.63      0.64      0.63       152

[[28  8  3  3]
 [ 7 23  0  4]
 [ 7  0  2  7]
 [10  0  6 44]] 0.8410912455259881