In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [3]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [4]:
df = pd.read_csv("chemberta_idotdo_MLM.csv" , index_col=0)
df

            0         1         2  ...       381       382       383
0    0.494268  0.118459  0.120281  ...  0.492498 -0.248157 -0.081414
1    0.005436 -0.024954  0.233959  ... -0.089507 -0.657648 -0.510167
2    0.428353  0.077683  0.119967  ...  0.502577 -0.285817 -0.060027
3   -0.220455 -0.173326  0.087070  ...  0.161007 -0.621344 -0.184317
4    0.191558  0.217486  0.072423  ... -0.195638  0.126749 -0.157562
..        ...       ...       ...  ...       ...       ...       ...
755  0.096448 -0.196375  0.009497  ...  0.079903 -0.715149  0.109028
756 -0.036910 -0.076283  0.432522  ... -0.039481 -0.394193 -0.475724
757  0.117963 -0.602324 -0.078357  ... -0.042870 -0.519331 -0.392036
758  0.103492  0.119691  0.062620  ...  0.099882 -0.428025  0.024234
759  0.497698  0.152799  0.109580  ...  0.458886 -0.263986 -0.081177

[760 rows x 384 columns]

In [5]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [6]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [7]:
X = df.iloc[:, :]
X

            0         1         2  ...       381       382       383
0    0.494268  0.118459  0.120281  ...  0.492498 -0.248157 -0.081414
1    0.005436 -0.024954  0.233959  ... -0.089507 -0.657648 -0.510167
2    0.428353  0.077683  0.119967  ...  0.502577 -0.285817 -0.060027
3   -0.220455 -0.173326  0.087070  ...  0.161007 -0.621344 -0.184317
4    0.191558  0.217486  0.072423  ... -0.195638  0.126749 -0.157562
..        ...       ...       ...  ...       ...       ...       ...
755  0.096448 -0.196375  0.009497  ...  0.079903 -0.715149  0.109028
756 -0.036910 -0.076283  0.432522  ... -0.039481 -0.394193 -0.475724
757  0.117963 -0.602324 -0.078357  ... -0.042870 -0.519331 -0.392036
758  0.103492  0.119691  0.062620  ...  0.099882 -0.428025  0.024234
759  0.497698  0.152799  0.109580  ...  0.458886 -0.263986 -0.081177

[760 rows x 384 columns]

In [8]:
X_scaled = StandardScaler().fit_transform(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [10]:
# using default values

clf = KNeighborsClassifier()

In [11]:
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [14]:
ypred = clf.predict(X_test)

In [16]:
print("knn chemberta mlm")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

knn chemberta mlm
              precision    recall  f1-score   support

          AA       0.53      0.74      0.62        42
          AI       0.67      0.71      0.69        34
          IA       0.50      0.25      0.33        16
          II       0.80      0.67      0.73        60

    accuracy                           0.65       152
   macro avg       0.63      0.59      0.59       152
weighted avg       0.67      0.65      0.65       152

[[31  6  2  3]
 [ 6 24  0  4]
 [ 8  1  4  3]
 [13  5  2 40]]

np.float64(0.7852092573140368)

In [17]:
# using default values

clf = KNeighborsClassifier(weights='distance')

In [18]:
clf.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [19]:
ypred = clf.predict(X_test)

In [20]:
print("knn chemberta mtr weight = distance")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

knn chemberta mtr weight = distance
              precision    recall  f1-score   support

          AA       0.62      0.76      0.68        42
          AI       0.78      0.74      0.76        34
          IA       0.33      0.19      0.24        16
          II       0.78      0.77      0.77        60

    accuracy                           0.70       152
   macro avg       0.63      0.61      0.61       152
weighted avg       0.69      0.70      0.69       152

[[32  4  3  3]
 [ 5 25  0  4]
 [ 7  0  3  6]
 [ 8  3  3 46]]

np.float64(0.779175055438842)