In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, matthews_corrcoef

In [2]:
df = pd.read_csv("chemberta_idotdo_MTR.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.098624,0.042223,-0.195243,0.209923,0.247522,-0.200116,0.130730,-0.078926,0.217784,-0.182055,...,-0.083785,-0.015257,0.208670,-0.099257,0.036652,0.011307,-0.015858,-0.034473,0.080340,0.090633
1,-0.195444,-0.006335,-0.125551,0.019175,-0.001245,-0.109488,0.118288,-0.345516,0.020197,-0.318505,...,0.153339,-0.094293,0.072913,-0.126550,0.012802,-0.071275,0.245102,-0.169543,-0.080592,-0.355988
2,0.019954,0.011441,-0.158951,0.221017,0.246666,-0.214977,0.122784,-0.182540,0.290653,-0.235725,...,-0.117349,-0.072634,0.212387,0.004530,-0.039211,-0.015519,0.015888,-0.153794,0.055760,0.118594
3,0.208809,0.168003,-0.015691,-0.009882,0.152641,0.031507,-0.038857,-0.054616,0.173442,-0.060251,...,-0.128801,-0.175998,0.109642,-0.068736,0.190212,-0.180588,0.214342,-0.124051,-0.300908,-0.076737
4,-0.041897,-0.128232,-0.096629,-0.068780,0.078374,-0.041795,0.128524,0.017905,0.171965,-0.143606,...,0.128640,-0.195388,0.355525,-0.314848,0.265437,-0.197671,0.041610,0.207000,-0.186747,0.126672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,-0.099143,0.104436,0.011019,-0.165326,0.135885,-0.002735,-0.053308,0.116025,0.044211,-0.000038,...,-0.215827,0.197586,0.226231,-0.037536,0.056611,-0.155834,-0.153475,0.095045,-0.010944,-0.130073
756,0.011156,0.046114,0.019320,0.022109,0.234958,0.037306,0.037335,0.020181,0.005356,-0.084363,...,-0.043167,0.147757,0.299443,0.175839,-0.089705,-0.102291,-0.110185,0.237602,0.147709,-0.066069
757,-0.224795,0.074084,-0.111290,-0.070322,0.037394,-0.100532,0.073335,-0.244298,0.019439,-0.383307,...,0.119012,-0.095294,0.093073,-0.222050,0.105182,-0.022975,0.171083,-0.198204,-0.140231,-0.261504
758,-0.104002,0.089321,-0.083992,0.218112,0.071453,-0.035407,0.231394,-0.124874,-0.125678,0.000591,...,0.142494,0.000984,0.231777,0.024092,0.036001,0.095570,-0.203001,-0.023051,0.020927,-0.080840
759,0.067812,-0.030397,-0.156415,0.200837,0.227610,-0.212452,0.127864,-0.159986,0.242586,-0.216630,...,-0.167850,-0.079812,0.180793,-0.038872,-0.023832,0.018703,-0.038679,-0.135613,0.073865,0.017983

In [3]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [4]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [5]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.098624,0.042223,-0.195243,0.209923,0.247522,-0.200116,0.130730,-0.078926,0.217784,-0.182055,...,-0.083785,-0.015257,0.208670,-0.099257,0.036652,0.011307,-0.015858,-0.034473,0.080340,0.090633
1,-0.195444,-0.006335,-0.125551,0.019175,-0.001245,-0.109488,0.118288,-0.345516,0.020197,-0.318505,...,0.153339,-0.094293,0.072913,-0.126550,0.012802,-0.071275,0.245102,-0.169543,-0.080592,-0.355988
2,0.019954,0.011441,-0.158951,0.221017,0.246666,-0.214977,0.122784,-0.182540,0.290653,-0.235725,...,-0.117349,-0.072634,0.212387,0.004530,-0.039211,-0.015519,0.015888,-0.153794,0.055760,0.118594
3,0.208809,0.168003,-0.015691,-0.009882,0.152641,0.031507,-0.038857,-0.054616,0.173442,-0.060251,...,-0.128801,-0.175998,0.109642,-0.068736,0.190212,-0.180588,0.214342,-0.124051,-0.300908,-0.076737
4,-0.041897,-0.128232,-0.096629,-0.068780,0.078374,-0.041795,0.128524,0.017905,0.171965,-0.143606,...,0.128640,-0.195388,0.355525,-0.314848,0.265437,-0.197671,0.041610,0.207000,-0.186747,0.126672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,-0.099143,0.104436,0.011019,-0.165326,0.135885,-0.002735,-0.053308,0.116025,0.044211,-0.000038,...,-0.215827,0.197586,0.226231,-0.037536,0.056611,-0.155834,-0.153475,0.095045,-0.010944,-0.130073
756,0.011156,0.046114,0.019320,0.022109,0.234958,0.037306,0.037335,0.020181,0.005356,-0.084363,...,-0.043167,0.147757,0.299443,0.175839,-0.089705,-0.102291,-0.110185,0.237602,0.147709,-0.066069
757,-0.224795,0.074084,-0.111290,-0.070322,0.037394,-0.100532,0.073335,-0.244298,0.019439,-0.383307,...,0.119012,-0.095294,0.093073,-0.222050,0.105182,-0.022975,0.171083,-0.198204,-0.140231,-0.261504
758,-0.104002,0.089321,-0.083992,0.218112,0.071453,-0.035407,0.231394,-0.124874,-0.125678,0.000591,...,0.142494,0.000984,0.231777,0.024092,0.036001,0.095570,-0.203001,-0.023051,0.020927,-0.080840
759,0.067812,-0.030397,-0.156415,0.200837,0.227610,-0.212452,0.127864,-0.159986,0.242586,-0.216630,...,-0.167850,-0.079812,0.180793,-0.038872,-0.023832,0.018703,-0.038679,-0.135613,0.073865,0.017983

In [6]:
X_scaled = StandardScaler().fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [11]:
model = KNeighborsClassifier()
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [12]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree')

In [8]:
clf = KNeighborsClassifier(algorithm='ball_tree')

In [9]:
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree')

In [10]:
ypred = clf.predict(X_test)

In [11]:
print("knn chemberta mtr")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

knn chemberta mtr
              precision    recall  f1-score   support

          AA       0.53      0.76      0.63        42
          AI       0.82      0.68      0.74        34
          IA       0.44      0.25      0.32        16
          II       0.78      0.72      0.75        60

    accuracy                           0.67       152
   macro avg       0.65      0.60      0.61       152
weighted avg       0.69      0.67      0.67       152

[[32  5  2  3]
 [ 7 23  0  4]
 [ 7  0  4  5]
 [14  0  3 43]]
0.8693946823009702
0.5378590152579225

In [12]:
#External test:
df_test = pd.read_csv("chemberta_test_MTR.csv" , index_col=0)
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("knn chemberta mtr")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

knn chemberta mtr
              precision    recall  f1-score   support

          AA       0.03      1.00      0.05         2
          AI       0.10      0.07      0.08        27
          IA       0.19      0.38      0.25         8
          II       1.00      0.03      0.05        74

    accuracy                           0.08       111
   macro avg       0.33      0.37      0.11       111
weighted avg       0.70      0.08      0.07       111

[[ 2  0  0  0]
 [24  2  1  0]
 [ 5  0  3  0]
 [41 19 12  2]]
0.5717016461069919
0.0019233899261959378

In [17]:
model = KNeighborsClassifier(weights='distance')
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(weights='distance'),
             n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [18]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=6, weights='distance')

In [13]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=6, weights='distance')

In [14]:
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=6, weights='distance')

In [15]:
ypred = clf.predict(X_test)

In [16]:
print("knn chemberta mtr weight = distance")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

knn chemberta mtr weight = distance
              precision    recall  f1-score   support

          AA       0.53      0.69      0.60        42
          AI       0.77      0.71      0.74        34
          IA       0.29      0.12      0.17        16
          II       0.80      0.78      0.79        60

    accuracy                           0.67       152
   macro avg       0.60      0.58      0.58       152
weighted avg       0.66      0.67      0.66       152

[[29  7  3  3]
 [ 7 24  0  3]
 [ 8  0  2  6]
 [11  0  2 47]]
0.8473735898473997
0.5320392547809898

In [17]:
#External test:
df_test = pd.read_csv("chemberta_test_MTR.csv" , index_col=0)
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("knn chemberta mtr")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

knn chemberta mtr
              precision    recall  f1-score   support

          AA       0.03      1.00      0.06         2
          AI       0.15      0.15      0.15        27
          IA       0.28      0.62      0.38         8
          II       1.00      0.07      0.13        74

    accuracy                           0.14       111
   macro avg       0.37      0.46      0.18       111
weighted avg       0.72      0.14      0.15       111

[[ 2  0  0  0]
 [22  4  1  0]
 [ 3  0  5  0]
 [35 22 12  5]]
0.6295568135924736
0.06494476877552664

# **For Bemis-Murcko scaffold-splitting, run the following cells:**

In [7]:
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

In [8]:
df_total = pd.read_csv('final_total.csv')
smiles_list = [df_total.loc[i, 'smiles'] for i in range(len(df_total))]

In [9]:
def generate_scaffold(smiles, include_chirality=False):
    """
    Generate the Bemis-Murcko scaffold for a given SMILES string.
    
    Parameters:
    -----------
    smiles : str
        SMILES representation of the molecule
    include_chirality : bool
        Whether to include chirality in the scaffold
    
    Returns:
    --------
    str : Scaffold SMILES string
    """
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return smiles
        scaffold = MurckoScaffold.MurckoScaffoldSmiles(
            mol=mol, 
            includeChirality=include_chirality
        )
        return scaffold
    except:
        return smiles

def scaffold_split(X, y, smiles_list, frac_train=0.8, frac_test=0.2, seed=None):
    """
    Split data by Bemis-Murcko scaffolds.
    
    Parameters:
    -----------
    X : array-like
        Feature matrix (fingerprints)
    y : array-like
        Target labels
    smiles_list : list
        List of SMILES strings for each molecule
    frac_train : float
        Fraction of data for training
    frac_test : float
        Fraction of data for test
    seed : int or None
        Random seed for reproducibility
    
    Returns:
    --------
    tuple : (X_train, X_test, y_train, y_test, 
             idx_train, idx_test)
    """
    n_samples = len(smiles_list)
    
    # Group molecules by scaffold
    scaffolds = defaultdict(list)
    for idx, smiles in enumerate(smiles_list):
        scaffold = generate_scaffold(smiles, include_chirality=True)
        scaffolds[scaffold].append(idx)
    
    # Sort scaffolds by size (largest first)
    sorted_scaffolds = sorted(
        scaffolds.items(), 
        key=lambda x: len(x[1]), 
        reverse=True
    )
    
    # Calculate target sizes
    train_cutoff = int(frac_train * n_samples)
    
    train_idx = []
    test_idx = []
    
    # Assign entire scaffold groups to splits
    for scaffold, indices in sorted_scaffolds:
        if len(train_idx) + len(indices) <= train_cutoff:
            train_idx.extend(indices)
        else:
            test_idx.extend(indices)
    
    # Convert to numpy arrays if needed
    X = np.array(X)
    y = np.array(y)
    
    # Create splits
    X_train = X[train_idx]
    X_test = X[test_idx]
    
    y_train = y[train_idx]
    y_test = y[test_idx]
    
    print(f"Scaffold split results:")
    print(f"  Training:   {len(train_idx)} molecules ({len(train_idx)/n_samples*100:.1f}%)")
    print(f"  Test:       {len(test_idx)} molecules ({len(test_idx)/n_samples*100:.1f}%)")
    print(f"  Unique scaffolds: {len(scaffolds)}")
    
    return (X_train, X_test, 
            y_train, y_test,
            train_idx, test_idx)

In [10]:
# Perform scaffold split
X_train, X_test, y_train, y_test, idx_train, idx_test = scaffold_split(
    X_scaled, 
    y, 
    smiles_list,
    frac_train=0.8,
    frac_test=0.2,
    seed=42
)

print(f"\nShape of splits:")
print(f"  X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"  X_test: {X_test.shape}, y_test: {y_test.shape}")

Scaffold split results:
  Training:   608 molecules (80.0%)
  Test:       152 molecules (20.0%)
  Unique scaffolds: 250

Shape of splits:
  X_train: (608, 384), y_train: (608,)
  X_test: (152, 384), y_test: (152,)

In [26]:
model = KNeighborsClassifier()
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, scoring='matthews_corrcoef', n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='matthews_corrcoef')

In [27]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=3)

In [28]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=3)
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)

In [29]:
print("with scaffold splitting")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

with scaffold splitting
              precision    recall  f1-score   support

          AA       0.48      0.57      0.52        35
          AI       0.72      0.85      0.78        39
          IA       0.27      0.36      0.31        11
          II       0.84      0.61      0.71        67

    accuracy                           0.64       152
   macro avg       0.57      0.60      0.58       152
weighted avg       0.68      0.64      0.65       152

[[20  4  6  5]
 [ 6 33  0  0]
 [ 3  1  4  3]
 [13  8  5 41]]
0.8060386960943503
0.50620337631037

In [30]:
#External test:
df_test = pd.read_csv("chemberta_test_MTR.csv" , index_col=0)
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("knn chemberta mtr")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

knn chemberta mtr
              precision    recall  f1-score   support

          AA       0.03      1.00      0.06         2
          AI       0.19      0.19      0.19        27
          IA       0.42      0.62      0.50         8
          II       0.83      0.07      0.12        74

    accuracy                           0.15       111
   macro avg       0.37      0.47      0.22       111
weighted avg       0.63      0.15      0.17       111

[[ 2  0  0  0]
 [20  5  1  1]
 [ 3  0  5  0]
 [41 22  6  5]]
0.6643489091437731
0.07439625801743717

In [11]:
model = KNeighborsClassifier(weights='distance')
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, scoring='matthews_corrcoef', n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(weights='distance'),
             n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='matthews_corrcoef')

In [12]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=3, weights='distance')

In [13]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=3, weights='distance')
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)

In [14]:
print("with scaffold splitting")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

with scaffold splitting
              precision    recall  f1-score   support

          AA       0.53      0.57      0.55        35
          AI       0.71      0.82      0.76        39
          IA       0.21      0.36      0.27        11
          II       0.82      0.61      0.70        67

    accuracy                           0.64       152
   macro avg       0.57      0.59      0.57       152
weighted avg       0.68      0.64      0.65       152

[[20  4  6  5]
 [ 6 32  0  1]
 [ 3  1  4  3]
 [ 9  8  9 41]]
0.8052628906959476
0.4983724155023064