In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [2]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [3]:
df = pd.read_csv("chemberta_idotdo_MTR.csv" , index_col=0)
df

            0         1         2  ...       381       382       383
0    0.098624  0.042223 -0.195243  ... -0.034473  0.080340  0.090633
1   -0.195444 -0.006335 -0.125551  ... -0.169543 -0.080592 -0.355988
2    0.019954  0.011441 -0.158951  ... -0.153794  0.055760  0.118594
3    0.208809  0.168003 -0.015691  ... -0.124051 -0.300908 -0.076737
4   -0.041897 -0.128232 -0.096629  ...  0.207000 -0.186747  0.126672
..        ...       ...       ...  ...       ...       ...       ...
755 -0.099143  0.104436  0.011019  ...  0.095045 -0.010944 -0.130073
756  0.011156  0.046114  0.019320  ...  0.237602  0.147709 -0.066069
757 -0.224795  0.074084 -0.111290  ... -0.198204 -0.140231 -0.261504
758 -0.104002  0.089321 -0.083992  ... -0.023051  0.020927 -0.080840
759  0.067812 -0.030397 -0.156415  ... -0.135613  0.073865  0.017983

[760 rows x 384 columns]

In [4]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [5]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [6]:
X = df.iloc[:, :]
X

            0         1         2  ...       381       382       383
0    0.098624  0.042223 -0.195243  ... -0.034473  0.080340  0.090633
1   -0.195444 -0.006335 -0.125551  ... -0.169543 -0.080592 -0.355988
2    0.019954  0.011441 -0.158951  ... -0.153794  0.055760  0.118594
3    0.208809  0.168003 -0.015691  ... -0.124051 -0.300908 -0.076737
4   -0.041897 -0.128232 -0.096629  ...  0.207000 -0.186747  0.126672
..        ...       ...       ...  ...       ...       ...       ...
755 -0.099143  0.104436  0.011019  ...  0.095045 -0.010944 -0.130073
756  0.011156  0.046114  0.019320  ...  0.237602  0.147709 -0.066069
757 -0.224795  0.074084 -0.111290  ... -0.198204 -0.140231 -0.261504
758 -0.104002  0.089321 -0.083992  ... -0.023051  0.020927 -0.080840
759  0.067812 -0.030397 -0.156415  ... -0.135613  0.073865  0.017983

[760 rows x 384 columns]

In [7]:
X_scaled = StandardScaler().fit_transform(X)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [11]:
# using default values

clf = SVC(probability=True,kernel='rbf', random_state=42)

In [12]:
clf.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [13]:
ypred = clf.predict(X_test)

In [15]:
print("svm chemberta mtr")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr
              precision    recall  f1-score   support

          AA       0.58      0.81      0.67        42
          AI       0.86      0.71      0.77        34
          IA       0.50      0.12      0.20        16
          II       0.77      0.78      0.78        60

    accuracy                           0.70       152
   macro avg       0.68      0.61      0.61       152
weighted avg       0.71      0.70      0.69       152

[[34  3  1  4]
 [ 6 24  0  4]
 [ 8  0  2  6]
 [11  1  1 47]] 0.8389445708839092

In [16]:
# using default values

clf = SVC(probability=True,kernel='linear', random_state=42)

In [17]:
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [18]:
ypred = clf.predict(X_test)

In [20]:
print("svm chemberta mtr kernel linear")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr kernel linear
              precision    recall  f1-score   support

          AA       0.48      0.52      0.50        42
          AI       0.62      0.62      0.62        34
          IA       0.30      0.38      0.33        16
          II       0.71      0.62      0.66        60

    accuracy                           0.57       152
   macro avg       0.53      0.53      0.53       152
weighted avg       0.58      0.57      0.57       152

[[22  9  6  5]
 [ 7 21  1  5]
 [ 4  1  6  5]
 [13  3  7 37]] 0.8195193355119826

In [21]:
# using default values

clf = SVC(probability=True,kernel='rbf', random_state=42, class_weight='balanced')

In [22]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', probability=True, random_state=42)

In [27]:
ypred = clf.predict(X_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
print("svm chemberta mtr rbf balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr rbf balanced
              precision    recall  f1-score   support

          AA       0.53      0.67      0.59        42
          AI       0.75      0.71      0.73        34
          IA       0.29      0.31      0.30        16
          II       0.80      0.67      0.73        60

    accuracy                           0.64       152
   macro avg       0.59      0.59      0.59       152
weighted avg       0.66      0.64      0.64       152

[[28  6  6  2]
 [ 6 24  0  4]
 [ 7  0  5  4]
 [12  2  6 40]] 0.8593567635387488

In [28]:
# using default values

clf = SVC(probability=True,kernel='linear', random_state=42 , class_weight='balanced')

In [29]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear', probability=True, random_state=42)

In [30]:
ypred = clf.predict(X_test)

In [31]:
print("svm chemberta mtr linear balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr linear balanced
              precision    recall  f1-score   support

          AA       0.59      0.57      0.58        42
          AI       0.60      0.62      0.61        34
          IA       0.29      0.38      0.32        16
          II       0.75      0.68      0.71        60

    accuracy                           0.61       152
   macro avg       0.55      0.56      0.56       152
weighted avg       0.62      0.61      0.61       152

[[24 10  5  3]
 [ 6 21  1  6]
 [ 4  1  6  5]
 [ 7  3  9 41]] 0.8165022953625894