In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, matthews_corrcoef

In [2]:
df = pd.read_csv("chemberta_idotdo_MLM.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.494268,0.118459,0.120281,0.582558,-0.301724,-0.248270,0.390228,0.199377,-0.209512,-0.093487,...,0.273344,-0.034014,-0.264945,0.181101,0.170081,-0.591491,0.241762,0.492498,-0.248157,-0.081414
1,0.005436,-0.024954,0.233959,0.497118,-0.151142,0.150918,0.206057,0.158802,0.084643,0.377474,...,-0.313733,0.401681,0.357527,0.083439,0.127597,0.567946,-0.214001,-0.089507,-0.657648,-0.510167
2,0.428353,0.077683,0.119967,0.572152,-0.296688,-0.288362,0.366442,0.203296,-0.137712,-0.136954,...,0.293401,-0.020694,-0.274401,0.165714,0.112009,-0.583639,0.235649,0.502577,-0.285817,-0.060027
3,-0.220455,-0.173326,0.087070,0.357093,-0.054140,0.141931,-0.005703,0.279797,0.166914,0.378540,...,-0.091736,0.205081,0.203580,0.118018,-0.133505,0.688311,-0.282882,0.161007,-0.621344,-0.184317
4,0.191558,0.217486,0.072423,-0.369289,-0.139498,-0.001433,0.266710,0.316668,-0.100810,0.161753,...,0.185053,0.213698,0.052138,0.286550,-0.169922,0.128030,-0.002733,-0.195638,0.126749,-0.157562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,0.096448,-0.196375,0.009497,0.315273,0.049928,0.010837,0.183218,0.300431,0.079193,0.091808,...,-0.100654,0.403718,-0.237127,0.093188,-0.004821,0.446861,-0.197323,0.079903,-0.715149,0.109028
756,-0.036910,-0.076283,0.432522,0.218235,0.434630,0.263829,-0.203598,0.158928,0.095107,0.047925,...,-0.004925,0.537577,0.210890,-0.086547,0.036483,0.408588,-0.197518,-0.039481,-0.394193,-0.475724
757,0.117963,-0.602324,-0.078357,0.696379,-0.058135,0.120637,-0.061482,-0.130316,-0.157715,0.288869,...,0.137320,0.183565,-0.055043,-0.228694,0.056281,0.679372,-0.254261,-0.042870,-0.519331,-0.392036
758,0.103492,0.119691,0.062620,-0.351092,0.144403,0.115062,0.038932,0.292200,0.353231,0.210809,...,-0.464454,-0.092176,0.156075,0.314978,-0.174536,0.566107,-0.320034,0.099882,-0.428025,0.024234
759,0.497698,0.152799,0.109580,0.599806,-0.302446,-0.280265,0.355941,0.193674,-0.187973,-0.118393,...,0.247110,-0.036532,-0.257301,0.179095,0.200968,-0.584045,0.268925,0.458886,-0.263986,-0.081177

In [3]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [4]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [5]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.494268,0.118459,0.120281,0.582558,-0.301724,-0.248270,0.390228,0.199377,-0.209512,-0.093487,...,0.273344,-0.034014,-0.264945,0.181101,0.170081,-0.591491,0.241762,0.492498,-0.248157,-0.081414
1,0.005436,-0.024954,0.233959,0.497118,-0.151142,0.150918,0.206057,0.158802,0.084643,0.377474,...,-0.313733,0.401681,0.357527,0.083439,0.127597,0.567946,-0.214001,-0.089507,-0.657648,-0.510167
2,0.428353,0.077683,0.119967,0.572152,-0.296688,-0.288362,0.366442,0.203296,-0.137712,-0.136954,...,0.293401,-0.020694,-0.274401,0.165714,0.112009,-0.583639,0.235649,0.502577,-0.285817,-0.060027
3,-0.220455,-0.173326,0.087070,0.357093,-0.054140,0.141931,-0.005703,0.279797,0.166914,0.378540,...,-0.091736,0.205081,0.203580,0.118018,-0.133505,0.688311,-0.282882,0.161007,-0.621344,-0.184317
4,0.191558,0.217486,0.072423,-0.369289,-0.139498,-0.001433,0.266710,0.316668,-0.100810,0.161753,...,0.185053,0.213698,0.052138,0.286550,-0.169922,0.128030,-0.002733,-0.195638,0.126749,-0.157562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,0.096448,-0.196375,0.009497,0.315273,0.049928,0.010837,0.183218,0.300431,0.079193,0.091808,...,-0.100654,0.403718,-0.237127,0.093188,-0.004821,0.446861,-0.197323,0.079903,-0.715149,0.109028
756,-0.036910,-0.076283,0.432522,0.218235,0.434630,0.263829,-0.203598,0.158928,0.095107,0.047925,...,-0.004925,0.537577,0.210890,-0.086547,0.036483,0.408588,-0.197518,-0.039481,-0.394193,-0.475724
757,0.117963,-0.602324,-0.078357,0.696379,-0.058135,0.120637,-0.061482,-0.130316,-0.157715,0.288869,...,0.137320,0.183565,-0.055043,-0.228694,0.056281,0.679372,-0.254261,-0.042870,-0.519331,-0.392036
758,0.103492,0.119691,0.062620,-0.351092,0.144403,0.115062,0.038932,0.292200,0.353231,0.210809,...,-0.464454,-0.092176,0.156075,0.314978,-0.174536,0.566107,-0.320034,0.099882,-0.428025,0.024234
759,0.497698,0.152799,0.109580,0.599806,-0.302446,-0.280265,0.355941,0.193674,-0.187973,-0.118393,...,0.247110,-0.036532,-0.257301,0.179095,0.200968,-0.584045,0.268925,0.458886,-0.263986,-0.081177

In [6]:
X_scaled = StandardScaler().fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [17]:
model = SVC()
params = {
    "C": [0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 1, 0.1, 0.01, 0.001],
    "kernel": ["linear", "rbf", "poly", "sigmoid"]
}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']})

In [18]:
grid.best_estimator_

SVC(C=1000, gamma=0.01)

In [8]:
clf = SVC(probability=True,kernel='rbf', random_state=42, C=1000, gamma=0.01)

In [9]:
clf.fit(X_train, y_train)

SVC(C=1000, gamma=0.01, probability=True, random_state=42)

In [10]:
ypred = clf.predict(X_test)

In [12]:
print("svm chemberta mlm")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

svm chemberta mlm
              precision    recall  f1-score   support

          AA       0.63      0.69      0.66        42
          AI       0.71      0.65      0.68        34
          IA       0.22      0.12      0.16        16
          II       0.73      0.80      0.76        60

    accuracy                           0.66       152
   macro avg       0.57      0.57      0.56       152
weighted avg       0.64      0.66      0.65       152

[[29  8  2  3]
 [ 3 22  1  8]
 [ 7  0  2  7]
 [ 7  1  4 48]]
0.7863774904787567
0.517840051489269

In [13]:
#External test:
df_test = pd.read_csv("chemberta_test_MLM.csv" , index_col=0)
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("svm chemberta mlm")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

svm chemberta mlm
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.00      0.00      0.00        27
          IA       0.00      0.00      0.00         8
          II       0.67      1.00      0.80        74

    accuracy                           0.67       111
   macro avg       0.17      0.25      0.20       111
weighted avg       0.44      0.67      0.53       111

[[ 0  0  0  2]
 [ 0  0  0 27]
 [ 0  0  0  8]
 [ 0  0  0 74]]
0.4768423720990259
0.0

/home/linu/anaconda3/envs/embedding/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/linu/anaconda3/envs/embedding/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/linu/anaconda3/envs/embedding/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [25]:
model = SVC(class_weight='balanced')
params = {
    "C": [0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 1, 0.1, 0.01, 0.001],
    "kernel": ["linear", "rbf", "poly", "sigmoid"]
}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(class_weight='balanced'), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']})

In [26]:
grid.best_estimator_

SVC(C=1000, class_weight='balanced', gamma=0.01)

In [14]:
clf = SVC(probability=True,kernel='rbf', random_state=42, C=1000, gamma=0.01, class_weight='balanced')

In [15]:
clf.fit(X_train, y_train)

SVC(C=1000, class_weight='balanced', gamma=0.01, probability=True,
    random_state=42)

In [16]:
ypred = clf.predict(X_test)

In [17]:
print("svm chemberta mlm rbf balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

svm chemberta mlm rbf balanced
              precision    recall  f1-score   support

          AA       0.63      0.69      0.66        42
          AI       0.71      0.65      0.68        34
          IA       0.20      0.12      0.15        16
          II       0.72      0.78      0.75        60

    accuracy                           0.66       152
   macro avg       0.57      0.56      0.56       152
weighted avg       0.64      0.66      0.65       152

[[29  8  2  3]
 [ 3 22  1  8]
 [ 7  0  2  7]
 [ 7  1  5 47]]
0.7850242873892205
0.5092449427298084

In [18]:
#External test:
df_test = pd.read_csv("chemberta_test_MLM.csv" , index_col=0)
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("svm chemberta mlm")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

svm chemberta mlm
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.00      0.00      0.00        27
          IA       0.00      0.00      0.00         8
          II       0.67      1.00      0.80        74

    accuracy                           0.67       111
   macro avg       0.17      0.25      0.20       111
weighted avg       0.44      0.67      0.53       111

[[ 0  0  0  2]
 [ 0  0  0 27]
 [ 0  0  0  8]
 [ 0  0  0 74]]
0.4773578606917908
0.0

/home/linu/anaconda3/envs/embedding/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/linu/anaconda3/envs/embedding/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/linu/anaconda3/envs/embedding/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# **For Bemis-Murcko scaffold-splitting, run the following cells:**

In [7]:
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

In [8]:
df_total = pd.read_csv('final_total.csv')
smiles_list = [df_total.loc[i, 'smiles'] for i in range(len(df_total))]

In [9]:
def generate_scaffold(smiles, include_chirality=False):
    """
    Generate the Bemis-Murcko scaffold for a given SMILES string.
    
    Parameters:
    -----------
    smiles : str
        SMILES representation of the molecule
    include_chirality : bool
        Whether to include chirality in the scaffold
    
    Returns:
    --------
    str : Scaffold SMILES string
    """
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return smiles
        scaffold = MurckoScaffold.MurckoScaffoldSmiles(
            mol=mol, 
            includeChirality=include_chirality
        )
        return scaffold
    except:
        return smiles

def scaffold_split(X, y, smiles_list, frac_train=0.8, frac_test=0.2, seed=None):
    """
    Split data by Bemis-Murcko scaffolds.
    
    Parameters:
    -----------
    X : array-like
        Feature matrix (fingerprints)
    y : array-like
        Target labels
    smiles_list : list
        List of SMILES strings for each molecule
    frac_train : float
        Fraction of data for training
    frac_test : float
        Fraction of data for test
    seed : int or None
        Random seed for reproducibility
    
    Returns:
    --------
    tuple : (X_train, X_test, y_train, y_test, 
             idx_train, idx_test)
    """
    n_samples = len(smiles_list)
    
    # Group molecules by scaffold
    scaffolds = defaultdict(list)
    for idx, smiles in enumerate(smiles_list):
        scaffold = generate_scaffold(smiles, include_chirality=True)
        scaffolds[scaffold].append(idx)
    
    # Sort scaffolds by size (largest first)
    sorted_scaffolds = sorted(
        scaffolds.items(), 
        key=lambda x: len(x[1]), 
        reverse=True
    )
    
    # Calculate target sizes
    train_cutoff = int(frac_train * n_samples)
    
    train_idx = []
    test_idx = []
    
    # Assign entire scaffold groups to splits
    for scaffold, indices in sorted_scaffolds:
        if len(train_idx) + len(indices) <= train_cutoff:
            train_idx.extend(indices)
        else:
            test_idx.extend(indices)
    
    # Convert to numpy arrays if needed
    X = np.array(X)
    y = np.array(y)
    
    # Create splits
    X_train = X[train_idx]
    X_test = X[test_idx]
    
    y_train = y[train_idx]
    y_test = y[test_idx]
    
    print(f"Scaffold split results:")
    print(f"  Training:   {len(train_idx)} molecules ({len(train_idx)/n_samples*100:.1f}%)")
    print(f"  Test:       {len(test_idx)} molecules ({len(test_idx)/n_samples*100:.1f}%)")
    print(f"  Unique scaffolds: {len(scaffolds)}")
    
    return (X_train, X_test, 
            y_train, y_test,
            train_idx, test_idx)

In [10]:
# Perform scaffold split
X_train, X_test, y_train, y_test, idx_train, idx_test = scaffold_split(
    X_scaled, 
    y, 
    smiles_list,
    frac_train=0.8,
    frac_test=0.2,
    seed=42
)

print(f"\nShape of splits:")
print(f"  X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"  X_test: {X_test.shape}, y_test: {y_test.shape}")

Scaffold split results:
  Training:   608 molecules (80.0%)
  Test:       152 molecules (20.0%)
  Unique scaffolds: 250

Shape of splits:
  X_train: (608, 384), y_train: (608,)
  X_test: (152, 384), y_test: (152,)

In [11]:
model = SVC(class_weight='balanced')
params = {
    "C": [0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 1, 0.1, 0.01, 0.001],
    "kernel": ["linear", "rbf", "poly", "sigmoid"]
}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(class_weight='balanced'), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']})

In [12]:
grid.best_estimator_

SVC(C=1, class_weight='balanced', gamma=0.1)

In [13]:
clf = SVC(probability=True, C=1, gamma=0.1, class_weight='balanced', random_state=42)
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)

In [14]:
print("svm chemberta mlm")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

svm chemberta mlm
              precision    recall  f1-score   support

          AA       0.53      0.23      0.32        35
          AI       0.64      0.23      0.34        39
          IA       0.20      0.09      0.12        11
          II       0.50      0.88      0.64        67

    accuracy                           0.51       152
   macro avg       0.47      0.36      0.36       152
weighted avg       0.52      0.51      0.45       152

[[ 8  4  1 22]
 [ 3  9  0 27]
 [ 0  0  1 10]
 [ 4  1  3 59]]
0.7607794871163724
0.22783327707860448

In [15]:
#External test:
df_test = pd.read_csv("chemberta_test_MLM.csv" , index_col=0)
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("svm chemberta mtr")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

svm chemberta mtr
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.00      0.00      0.00        27
          IA       0.00      0.00      0.00         8
          II       0.67      1.00      0.80        74

    accuracy                           0.67       111
   macro avg       0.17      0.25      0.20       111
weighted avg       0.44      0.67      0.53       111

[[ 0  0  0  2]
 [ 0  0  0 27]
 [ 0  0  0  8]
 [ 0  0  0 74]]
0.518621148965308
0.0