In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score

In [11]:
df = pd.read_csv("ido&tdo_mol2vec_100.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-1.453280,3.135438,-5.660918,-3.033242,-7.617049,-2.716532,-7.720714,-6.865502,-3.826457,-10.098655,...,12.327754,6.312767,-3.286225,-9.455015,6.964842,-18.937403,2.750869,16.501455,-6.681480,-4.273498
1,-3.853994,6.813040,-5.372699,-10.387832,-7.475365,-7.042470,-8.528316,-9.411233,-4.238024,-7.068585,...,14.356148,6.834394,-6.223803,-8.759715,16.309746,-23.847692,5.861533,19.511469,-11.849033,-6.109491
2,-1.180174,4.254755,-4.536231,-3.562603,-7.379086,-2.324686,-7.427113,-5.083071,-4.248663,-10.196310,...,12.481528,6.821596,-3.761701,-8.469126,7.075356,-18.553902,3.375219,16.544933,-6.834486,-4.556705
3,-0.524230,4.466556,-6.165118,-4.102696,-10.611167,-1.818723,-5.979259,-5.709599,-6.038849,-13.244520,...,12.143913,7.398972,-5.778560,-13.840563,7.989666,-23.088305,-0.075834,17.757563,-11.344548,-4.462366
4,-2.448480,3.668087,-4.891652,0.175000,-3.162153,-0.902194,-5.511296,-5.637284,0.345561,-10.797401,...,9.505338,3.902331,-7.623469,-8.973467,2.909839,-16.380924,1.064918,12.309534,-5.863398,0.419550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.039092,0.848239,-3.001012,-3.508708,-9.706405,-2.770367,-4.451425,-7.632759,-1.270038,-8.030599,...,12.036806,3.439590,-6.031008,-13.486352,6.996030,-18.041094,2.354814,8.362853,-13.254911,0.908203
756,1.353009,2.167352,-1.366708,-2.364529,-9.814615,-1.395514,-4.151305,-5.806736,-2.388004,-8.079832,...,9.126462,2.641247,-6.271195,-9.573577,4.639385,-16.821928,2.525217,9.565623,-11.529164,0.066681
757,-2.602998,7.125832,-4.669659,-10.372896,-8.373899,-5.247980,-9.301612,-8.637301,-1.214552,-7.111208,...,14.875299,8.092024,-4.372728,-11.463555,16.909105,-21.494097,4.570755,16.546633,-13.254592,-6.511065
758,-2.312877,-0.113580,0.816559,-0.219393,-5.586400,-2.550617,-2.000148,-9.507885,-2.465487,-12.263936,...,10.518041,3.871650,-4.892249,-9.578062,7.791412,-19.127460,5.459632,12.098536,-5.661181,2.037486
759,-1.734595,2.714000,-6.100870,-4.617870,-6.708008,-3.416954,-7.027505,-5.663856,-5.325977,-10.546162,...,11.494627,7.137109,-3.493536,-9.470264,6.638402,-19.514500,2.496200,16.008764,-6.865590,-4.034605

In [12]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [13]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [14]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-1.453280,3.135438,-5.660918,-3.033242,-7.617049,-2.716532,-7.720714,-6.865502,-3.826457,-10.098655,...,12.327754,6.312767,-3.286225,-9.455015,6.964842,-18.937403,2.750869,16.501455,-6.681480,-4.273498
1,-3.853994,6.813040,-5.372699,-10.387832,-7.475365,-7.042470,-8.528316,-9.411233,-4.238024,-7.068585,...,14.356148,6.834394,-6.223803,-8.759715,16.309746,-23.847692,5.861533,19.511469,-11.849033,-6.109491
2,-1.180174,4.254755,-4.536231,-3.562603,-7.379086,-2.324686,-7.427113,-5.083071,-4.248663,-10.196310,...,12.481528,6.821596,-3.761701,-8.469126,7.075356,-18.553902,3.375219,16.544933,-6.834486,-4.556705
3,-0.524230,4.466556,-6.165118,-4.102696,-10.611167,-1.818723,-5.979259,-5.709599,-6.038849,-13.244520,...,12.143913,7.398972,-5.778560,-13.840563,7.989666,-23.088305,-0.075834,17.757563,-11.344548,-4.462366
4,-2.448480,3.668087,-4.891652,0.175000,-3.162153,-0.902194,-5.511296,-5.637284,0.345561,-10.797401,...,9.505338,3.902331,-7.623469,-8.973467,2.909839,-16.380924,1.064918,12.309534,-5.863398,0.419550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.039092,0.848239,-3.001012,-3.508708,-9.706405,-2.770367,-4.451425,-7.632759,-1.270038,-8.030599,...,12.036806,3.439590,-6.031008,-13.486352,6.996030,-18.041094,2.354814,8.362853,-13.254911,0.908203
756,1.353009,2.167352,-1.366708,-2.364529,-9.814615,-1.395514,-4.151305,-5.806736,-2.388004,-8.079832,...,9.126462,2.641247,-6.271195,-9.573577,4.639385,-16.821928,2.525217,9.565623,-11.529164,0.066681
757,-2.602998,7.125832,-4.669659,-10.372896,-8.373899,-5.247980,-9.301612,-8.637301,-1.214552,-7.111208,...,14.875299,8.092024,-4.372728,-11.463555,16.909105,-21.494097,4.570755,16.546633,-13.254592,-6.511065
758,-2.312877,-0.113580,0.816559,-0.219393,-5.586400,-2.550617,-2.000148,-9.507885,-2.465487,-12.263936,...,10.518041,3.871650,-4.892249,-9.578062,7.791412,-19.127460,5.459632,12.098536,-5.661181,2.037486
759,-1.734595,2.714000,-6.100870,-4.617870,-6.708008,-3.416954,-7.027505,-5.663856,-5.325977,-10.546162,...,11.494627,7.137109,-3.493536,-9.470264,6.638402,-19.514500,2.496200,16.008764,-6.865590,-4.034605

In [15]:
X_scaled = StandardScaler().fit_transform(X)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [17]:
clf = SVC(kernel='rbf', random_state=42 , probability=True)

In [18]:
clf.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [19]:
y_pred = clf.predict(X_test)

In [21]:
print("mol2vec 100 svm")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

mol2vec 100 svm
              precision    recall  f1-score   support

          AA       0.58      0.81      0.67        42
          AI       0.86      0.71      0.77        34
          IA       0.75      0.19      0.30        16
          II       0.79      0.80      0.79        60

    accuracy                           0.72       152
   macro avg       0.74      0.63      0.64       152
weighted avg       0.74      0.72      0.70       152

[[34  4  1  3]
 [ 6 24  0  4]
 [ 7  0  3  6]
 [12  0  0 48]]

In [22]:
roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

np.float64(0.8229249338624339)

In [24]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [25]:
clf = SVC(kernel='linear' , random_state=42, probability=True)

In [26]:
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [27]:
y_pred = clf.predict(X_test)

In [28]:
print("mol2vec 300 svm kernel:linear")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

mol2vec 300 svm kernel:linear
              precision    recall  f1-score   support

          AA       0.57      0.69      0.62        42
          AI       0.77      0.59      0.67        34
          IA       0.29      0.25      0.27        16
          II       0.70      0.72      0.71        60

    accuracy                           0.63       152
   macro avg       0.58      0.56      0.57       152
weighted avg       0.64      0.63      0.63       152

[[29  6  3  4]
 [ 4 20  0 10]
 [ 8  0  4  4]
 [10  0  7 43]]

In [29]:
roc_auc()

np.float64(0.7751548883442264)

In [30]:
clf = SVC(kernel='rbf' , probability=True , class_weight='balanced' , random_state=42)

In [31]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', probability=True, random_state=42)

In [32]:
y_pred = clf.predict(X_test)

In [33]:
print("mol2vec 300 svm kernel:rbf class_weight = blanaced")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

mol2vec 300 svm kernel:rbf class_weight = blanaced
              precision    recall  f1-score   support

          AA       0.58      0.69      0.63        42
          AI       0.78      0.74      0.76        34
          IA       0.29      0.44      0.35        16
          II       0.83      0.63      0.72        60

    accuracy                           0.65       152
   macro avg       0.62      0.62      0.61       152
weighted avg       0.69      0.65      0.66       152

[[29  4  8  1]
 [ 6 25  0  3]
 [ 5  0  7  4]
 [10  3  9 38]]

np.float64(0.8512631788826641)

In [34]:
clf = SVC(kernel='linear',probability=True, class_weight='balanced' , random_state=42)

In [35]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear', probability=True, random_state=42)

In [37]:
y_pred = clf.predict(X_test)

In [49]:
print("mol2vec 300 svm kernel:linear class_weight=balanced")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

mol2vec 300 svm kernel:linear class_weight=balanced
              precision    recall  f1-score   support

          AA       0.52      0.62      0.57        42
          AI       0.70      0.62      0.66        34
          IA       0.29      0.50      0.36        16
          II       0.75      0.55      0.63        60

    accuracy                           0.58       152
   macro avg       0.56      0.57      0.55       152
weighted avg       0.63      0.58      0.59       152

[[26  7  7  2]
 [ 6 21  0  7]
 [ 6  0  8  2]
 [12  2 13 33]]

np.float64(0.7948001770152504)