In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score

In [2]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [3]:
df = pd.read_csv("ido&tdo_mol2vec_300.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,2.085246,-2.038275,-3.187863,8.277987,-1.473328,0.553464,-8.218416,-0.252765,5.976957,4.247883,...,-2.514272,7.614711,9.665213,-0.728455,-6.641990,-3.546622,-2.391847,-2.101916,-9.157832,-0.950201
1,2.164320,-0.599885,-3.328220,1.147567,-0.377009,1.582185,-8.842896,2.590148,0.420797,2.394938,...,-0.297584,9.834462,5.563936,-0.803765,-8.674775,-5.131175,-7.110797,-4.463612,-8.928865,-0.134624
2,1.625464,-2.320905,-3.008997,8.197512,-1.164763,1.174054,-7.366459,-0.087216,5.332006,4.546978,...,-2.660922,7.944535,10.210878,-0.773032,-6.216854,-2.984564,-2.426374,-1.107460,-8.576202,-1.356232
3,1.899230,-2.569787,-3.410282,10.681754,-2.165567,1.730022,-11.107470,0.863943,7.557280,3.846437,...,-2.524517,10.409447,12.572979,-1.090598,-4.617105,-2.671958,-3.982201,-0.524764,-10.007677,1.278735
4,2.579365,-0.462055,-2.360175,3.983515,-2.596048,1.301527,-7.521517,1.303868,3.315001,3.748758,...,-0.815256,6.375582,7.597131,-1.780380,-4.569449,-1.531563,-3.190221,-3.058734,-5.828879,0.447189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.712499,-3.792097,-2.364244,3.363801,-0.166023,-0.001611,-8.855852,0.661475,0.801766,0.544993,...,-0.136141,10.374839,5.031422,-1.267375,-7.197216,-3.841792,-7.744902,-5.256713,-8.899922,-1.219385
756,2.866019,-2.303052,-1.917922,4.422251,-0.717792,-0.029453,-7.384969,-0.278774,2.411067,0.309709,...,1.330587,8.674216,4.500438,-1.143635,-5.071250,-3.963346,-6.209548,-5.659032,-7.639552,-0.926412
757,2.318216,-1.639167,-2.197451,0.764488,0.522354,0.561993,-9.767791,1.646610,1.136305,1.585453,...,-0.579593,9.518148,5.871013,-0.282573,-9.717593,-5.270689,-6.158346,-3.637163,-9.239653,0.744431
758,2.228861,-3.710076,-1.460758,3.618860,1.509769,2.148596,-7.016947,-1.973611,5.845882,3.350458,...,-0.805335,5.618067,11.294125,-1.662612,-2.628362,-1.926153,-5.180820,-1.664173,-6.532691,-0.776828
759,1.402920,-1.705615,-3.531063,8.404659,-0.677054,1.040710,-8.085209,-0.074132,4.349245,4.007777,...,-2.217267,8.017588,9.256686,-0.542930,-6.837158,-3.086798,-3.267218,-2.825044,-8.359281,-1.440486

In [4]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [5]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [6]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,2.085246,-2.038275,-3.187863,8.277987,-1.473328,0.553464,-8.218416,-0.252765,5.976957,4.247883,...,-2.514272,7.614711,9.665213,-0.728455,-6.641990,-3.546622,-2.391847,-2.101916,-9.157832,-0.950201
1,2.164320,-0.599885,-3.328220,1.147567,-0.377009,1.582185,-8.842896,2.590148,0.420797,2.394938,...,-0.297584,9.834462,5.563936,-0.803765,-8.674775,-5.131175,-7.110797,-4.463612,-8.928865,-0.134624
2,1.625464,-2.320905,-3.008997,8.197512,-1.164763,1.174054,-7.366459,-0.087216,5.332006,4.546978,...,-2.660922,7.944535,10.210878,-0.773032,-6.216854,-2.984564,-2.426374,-1.107460,-8.576202,-1.356232
3,1.899230,-2.569787,-3.410282,10.681754,-2.165567,1.730022,-11.107470,0.863943,7.557280,3.846437,...,-2.524517,10.409447,12.572979,-1.090598,-4.617105,-2.671958,-3.982201,-0.524764,-10.007677,1.278735
4,2.579365,-0.462055,-2.360175,3.983515,-2.596048,1.301527,-7.521517,1.303868,3.315001,3.748758,...,-0.815256,6.375582,7.597131,-1.780380,-4.569449,-1.531563,-3.190221,-3.058734,-5.828879,0.447189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.712499,-3.792097,-2.364244,3.363801,-0.166023,-0.001611,-8.855852,0.661475,0.801766,0.544993,...,-0.136141,10.374839,5.031422,-1.267375,-7.197216,-3.841792,-7.744902,-5.256713,-8.899922,-1.219385
756,2.866019,-2.303052,-1.917922,4.422251,-0.717792,-0.029453,-7.384969,-0.278774,2.411067,0.309709,...,1.330587,8.674216,4.500438,-1.143635,-5.071250,-3.963346,-6.209548,-5.659032,-7.639552,-0.926412
757,2.318216,-1.639167,-2.197451,0.764488,0.522354,0.561993,-9.767791,1.646610,1.136305,1.585453,...,-0.579593,9.518148,5.871013,-0.282573,-9.717593,-5.270689,-6.158346,-3.637163,-9.239653,0.744431
758,2.228861,-3.710076,-1.460758,3.618860,1.509769,2.148596,-7.016947,-1.973611,5.845882,3.350458,...,-0.805335,5.618067,11.294125,-1.662612,-2.628362,-1.926153,-5.180820,-1.664173,-6.532691,-0.776828
759,1.402920,-1.705615,-3.531063,8.404659,-0.677054,1.040710,-8.085209,-0.074132,4.349245,4.007777,...,-2.217267,8.017588,9.256686,-0.542930,-6.837158,-3.086798,-3.267218,-2.825044,-8.359281,-1.440486

In [7]:
X_scaled = StandardScaler().fit_transform(X)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [9]:
clf = SVC(kernel='rbf', random_state=42, probability=True)

In [10]:
clf.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [11]:
y_pred = clf.predict(X_test)

In [13]:
print("mol2vec 300 svm")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

mol2vec 300 svm
              precision    recall  f1-score   support

          AA       0.59      0.81      0.68        42
          AI       0.83      0.71      0.76        34
          IA       0.50      0.12      0.20        16
          II       0.79      0.80      0.79        60

    accuracy                           0.71       152
   macro avg       0.68      0.61      0.61       152
weighted avg       0.71      0.71      0.69       152

[[34  4  1  3]
 [ 6 24  0  4]
 [ 8  0  2  6]
 [10  1  1 48]]

np.float64(0.8298980703392468)

In [14]:
clf = SVC(kernel='linear' , random_state=42, probability=True)

In [15]:
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [16]:
y_pred = clf.predict(X_test)

In [17]:
print("mol2vec 300 svm kernel:linear")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

mol2vec 300 svm kernel:linear
              precision    recall  f1-score   support

          AA       0.58      0.71      0.64        42
          AI       0.68      0.68      0.68        34
          IA       0.21      0.19      0.20        16
          II       0.71      0.62      0.66        60

    accuracy                           0.61       152
   macro avg       0.54      0.55      0.54       152
weighted avg       0.61      0.61      0.61       152

[[30  7  3  2]
 [ 5 23  0  6]
 [ 6  0  3  7]
 [11  4  8 37]]

np.float64(0.8139978213507625)

In [18]:
clf = SVC(kernel='rbf' , class_weight='balanced' , random_state=42, probability=True)

In [19]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', probability=True, random_state=42)

In [20]:
y_pred = clf.predict(X_test)

In [21]:
print("mol2vec 300 svm kernel:rbf class_weight = blanaced")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

mol2vec 300 svm kernel:rbf class_weight = blanaced
              precision    recall  f1-score   support

          AA       0.59      0.71      0.65        42
          AI       0.81      0.74      0.77        34
          IA       0.29      0.44      0.35        16
          II       0.83      0.63      0.72        60

    accuracy                           0.66       152
   macro avg       0.63      0.63      0.62       152
weighted avg       0.70      0.66      0.67       152

[[30  4  7  1]
 [ 6 25  0  3]
 [ 5  0  7  4]
 [10  2 10 38]]

np.float64(0.8558684932306256)

In [22]:
clf = SVC(kernel='linear', class_weight='balanced' , random_state=42, probability=True)

In [23]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear', probability=True, random_state=42)

In [24]:
y_pred = clf.predict(X_test)

In [25]:
print("mol2vec 300 svm kernel:linear class_weight=balanced")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
roc_auc()

mol2vec 300 svm kernel:linear class_weight=balanced
              precision    recall  f1-score   support

          AA       0.56      0.71      0.62        42
          AI       0.64      0.68      0.66        34
          IA       0.27      0.25      0.26        16
          II       0.74      0.58      0.65        60

    accuracy                           0.61       152
   macro avg       0.55      0.56      0.55       152
weighted avg       0.62      0.61      0.61       152

[[30  7  3  2]
 [ 4 23  1  6]
 [ 8  0  4  4]
 [12  6  7 35]]

np.float64(0.8129632061157798)