In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, matthews_corrcoef

In [2]:
df = pd.read_csv("ido&tdo_mol2vec_300.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,2.085246,-2.038275,-3.187863,8.277987,-1.473328,0.553464,-8.218416,-0.252765,5.976957,4.247883,...,-2.514272,7.614711,9.665213,-0.728455,-6.641990,-3.546622,-2.391847,-2.101916,-9.157832,-0.950201
1,2.164320,-0.599885,-3.328220,1.147567,-0.377009,1.582185,-8.842896,2.590148,0.420797,2.394938,...,-0.297584,9.834462,5.563936,-0.803765,-8.674775,-5.131175,-7.110797,-4.463612,-8.928865,-0.134624
2,1.625464,-2.320905,-3.008997,8.197512,-1.164763,1.174054,-7.366459,-0.087216,5.332006,4.546978,...,-2.660922,7.944535,10.210878,-0.773032,-6.216854,-2.984564,-2.426374,-1.107460,-8.576202,-1.356232
3,1.899230,-2.569787,-3.410282,10.681754,-2.165567,1.730022,-11.107470,0.863943,7.557280,3.846437,...,-2.524517,10.409447,12.572979,-1.090598,-4.617105,-2.671958,-3.982201,-0.524764,-10.007677,1.278735
4,2.579365,-0.462055,-2.360175,3.983515,-2.596048,1.301527,-7.521517,1.303868,3.315001,3.748758,...,-0.815256,6.375582,7.597131,-1.780380,-4.569449,-1.531563,-3.190221,-3.058734,-5.828879,0.447189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.712499,-3.792097,-2.364244,3.363801,-0.166023,-0.001611,-8.855852,0.661475,0.801766,0.544993,...,-0.136141,10.374839,5.031422,-1.267375,-7.197216,-3.841792,-7.744902,-5.256713,-8.899922,-1.219385
756,2.866019,-2.303052,-1.917922,4.422251,-0.717792,-0.029453,-7.384969,-0.278774,2.411067,0.309709,...,1.330587,8.674216,4.500438,-1.143635,-5.071250,-3.963346,-6.209548,-5.659032,-7.639552,-0.926412
757,2.318216,-1.639167,-2.197451,0.764488,0.522354,0.561993,-9.767791,1.646610,1.136305,1.585453,...,-0.579593,9.518148,5.871013,-0.282573,-9.717593,-5.270689,-6.158346,-3.637163,-9.239653,0.744431
758,2.228861,-3.710076,-1.460758,3.618860,1.509769,2.148596,-7.016947,-1.973611,5.845882,3.350458,...,-0.805335,5.618067,11.294125,-1.662612,-2.628362,-1.926153,-5.180820,-1.664173,-6.532691,-0.776828
759,1.402920,-1.705615,-3.531063,8.404659,-0.677054,1.040710,-8.085209,-0.074132,4.349245,4.007777,...,-2.217267,8.017588,9.256686,-0.542930,-6.837158,-3.086798,-3.267218,-2.825044,-8.359281,-1.440486

In [3]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [4]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [5]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,2.085246,-2.038275,-3.187863,8.277987,-1.473328,0.553464,-8.218416,-0.252765,5.976957,4.247883,...,-2.514272,7.614711,9.665213,-0.728455,-6.641990,-3.546622,-2.391847,-2.101916,-9.157832,-0.950201
1,2.164320,-0.599885,-3.328220,1.147567,-0.377009,1.582185,-8.842896,2.590148,0.420797,2.394938,...,-0.297584,9.834462,5.563936,-0.803765,-8.674775,-5.131175,-7.110797,-4.463612,-8.928865,-0.134624
2,1.625464,-2.320905,-3.008997,8.197512,-1.164763,1.174054,-7.366459,-0.087216,5.332006,4.546978,...,-2.660922,7.944535,10.210878,-0.773032,-6.216854,-2.984564,-2.426374,-1.107460,-8.576202,-1.356232
3,1.899230,-2.569787,-3.410282,10.681754,-2.165567,1.730022,-11.107470,0.863943,7.557280,3.846437,...,-2.524517,10.409447,12.572979,-1.090598,-4.617105,-2.671958,-3.982201,-0.524764,-10.007677,1.278735
4,2.579365,-0.462055,-2.360175,3.983515,-2.596048,1.301527,-7.521517,1.303868,3.315001,3.748758,...,-0.815256,6.375582,7.597131,-1.780380,-4.569449,-1.531563,-3.190221,-3.058734,-5.828879,0.447189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.712499,-3.792097,-2.364244,3.363801,-0.166023,-0.001611,-8.855852,0.661475,0.801766,0.544993,...,-0.136141,10.374839,5.031422,-1.267375,-7.197216,-3.841792,-7.744902,-5.256713,-8.899922,-1.219385
756,2.866019,-2.303052,-1.917922,4.422251,-0.717792,-0.029453,-7.384969,-0.278774,2.411067,0.309709,...,1.330587,8.674216,4.500438,-1.143635,-5.071250,-3.963346,-6.209548,-5.659032,-7.639552,-0.926412
757,2.318216,-1.639167,-2.197451,0.764488,0.522354,0.561993,-9.767791,1.646610,1.136305,1.585453,...,-0.579593,9.518148,5.871013,-0.282573,-9.717593,-5.270689,-6.158346,-3.637163,-9.239653,0.744431
758,2.228861,-3.710076,-1.460758,3.618860,1.509769,2.148596,-7.016947,-1.973611,5.845882,3.350458,...,-0.805335,5.618067,11.294125,-1.662612,-2.628362,-1.926153,-5.180820,-1.664173,-6.532691,-0.776828
759,1.402920,-1.705615,-3.531063,8.404659,-0.677054,1.040710,-8.085209,-0.074132,4.349245,4.007777,...,-2.217267,8.017588,9.256686,-0.542930,-6.837158,-3.086798,-3.267218,-2.825044,-8.359281,-1.440486

In [6]:
X_scaled = StandardScaler().fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [8]:
model = KNeighborsClassifier()
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [9]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=7)

In [8]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=7)

In [9]:
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=7)

In [10]:
y_pred = clf.predict(X_test)

In [11]:
print("mol2vec knn")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, y_pred))

mol2vec knn
              precision    recall  f1-score   support

          AA       0.54      0.81      0.65        42
          AI       0.83      0.74      0.78        34
          IA       0.67      0.25      0.36        16
          II       0.75      0.67      0.71        60

    accuracy                           0.68       152
   macro avg       0.70      0.62      0.63       152
weighted avg       0.70      0.68      0.67       152

[[34  3  0  5]
 [ 6 25  0  3]
 [ 7  0  4  5]
 [16  2  2 40]]
0.8647050140838307
0.54970761072153

In [12]:
#External test:
df_test = pd.read_csv("test_mol2vec_300.csv")
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("knn")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

knn
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.18      0.07      0.11        27
          IA       0.31      0.50      0.38         8
          II       0.81      0.35      0.49        74

    accuracy                           0.29       111
   macro avg       0.33      0.23      0.24       111
weighted avg       0.61      0.29      0.38       111

[[ 0  0  0  2]
 [23  2  0  2]
 [ 0  2  4  2]
 [32  7  9 26]]
0.4417423493105723
0.09686197305032937

In [15]:
model = KNeighborsClassifier(weights='distance')
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(weights='distance'),
             n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [16]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=8, weights='distance')

In [13]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=8, weights='distance')

In [14]:
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=8, weights='distance')

In [15]:
y_pred = clf.predict(X_test)

In [16]:
print("with scale and with weight=distance")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, y_pred))

with scale and with weight=distance
              precision    recall  f1-score   support

          AA       0.52      0.69      0.59        42
          AI       0.77      0.71      0.74        34
          IA       0.29      0.12      0.17        16
          II       0.74      0.72      0.73        60

    accuracy                           0.64       152
   macro avg       0.58      0.56      0.56       152
weighted avg       0.64      0.64      0.63       152

[[29  6  3  4]
 [ 6 24  0  4]
 [ 7  0  2  7]
 [14  1  2 43]]
0.8550557736493136
0.494962012227534

In [17]:
#External test:
df_test = pd.read_csv("test_mol2vec_300.csv")
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("knn")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

knn
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.20      0.11      0.14        27
          IA       0.31      0.50      0.38         8
          II       0.78      0.39      0.52        74

    accuracy                           0.32       111
   macro avg       0.32      0.25      0.26       111
weighted avg       0.59      0.32      0.41       111

[[ 0  0  0  2]
 [20  3  0  4]
 [ 0  2  4  2]
 [26 10  9 29]]
0.43510153765288984
0.0919468392101387

# **For Bemis-Murcko scaffold-splitting, run the following cells:**

In [7]:
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

In [8]:
df_total = pd.read_csv('final_total.csv')
smiles_list = [df_total.loc[i, 'smiles'] for i in range(len(df_total))]

In [9]:
def generate_scaffold(smiles, include_chirality=False):
    """
    Generate the Bemis-Murcko scaffold for a given SMILES string.
    
    Parameters:
    -----------
    smiles : str
        SMILES representation of the molecule
    include_chirality : bool
        Whether to include chirality in the scaffold
    
    Returns:
    --------
    str : Scaffold SMILES string
    """
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return smiles
        scaffold = MurckoScaffold.MurckoScaffoldSmiles(
            mol=mol, 
            includeChirality=include_chirality
        )
        return scaffold
    except:
        return smiles

def scaffold_split(X, y, smiles_list, frac_train=0.8, frac_test=0.2, seed=None):
    """
    Split data by Bemis-Murcko scaffolds.
    
    Parameters:
    -----------
    X : array-like
        Feature matrix (fingerprints)
    y : array-like
        Target labels
    smiles_list : list
        List of SMILES strings for each molecule
    frac_train : float
        Fraction of data for training
    frac_test : float
        Fraction of data for test
    seed : int or None
        Random seed for reproducibility
    
    Returns:
    --------
    tuple : (X_train, X_test, y_train, y_test, 
             idx_train, idx_test)
    """
    n_samples = len(smiles_list)
    
    # Group molecules by scaffold
    scaffolds = defaultdict(list)
    for idx, smiles in enumerate(smiles_list):
        scaffold = generate_scaffold(smiles, include_chirality=True)
        scaffolds[scaffold].append(idx)
    
    # Sort scaffolds by size (largest first)
    sorted_scaffolds = sorted(
        scaffolds.items(), 
        key=lambda x: len(x[1]), 
        reverse=True
    )
    
    # Calculate target sizes
    train_cutoff = int(frac_train * n_samples)
    
    train_idx = []
    test_idx = []
    
    # Assign entire scaffold groups to splits
    for scaffold, indices in sorted_scaffolds:
        if len(train_idx) + len(indices) <= train_cutoff:
            train_idx.extend(indices)
        else:
            test_idx.extend(indices)
    
    # Convert to numpy arrays if needed
    X = np.array(X)
    y = np.array(y)
    
    # Create splits
    X_train = X[train_idx]
    X_test = X[test_idx]
    
    y_train = y[train_idx]
    y_test = y[test_idx]
    
    print(f"Scaffold split results:")
    print(f"  Training:   {len(train_idx)} molecules ({len(train_idx)/n_samples*100:.1f}%)")
    print(f"  Test:       {len(test_idx)} molecules ({len(test_idx)/n_samples*100:.1f}%)")
    print(f"  Unique scaffolds: {len(scaffolds)}")
    
    return (X_train, X_test, 
            y_train, y_test,
            train_idx, test_idx)

In [10]:
# Perform scaffold split
X_train, X_test, y_train, y_test, idx_train, idx_test = scaffold_split(
    X_scaled, 
    y, 
    smiles_list,
    frac_train=0.8,
    frac_test=0.2,
    seed=42
)

print(f"\nShape of splits:")
print(f"  X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"  X_test: {X_test.shape}, y_test: {y_test.shape}")

Scaffold split results:
  Training:   608 molecules (80.0%)
  Test:       152 molecules (20.0%)
  Unique scaffolds: 250

Shape of splits:
  X_train: (608, 300), y_train: (608,)
  X_test: (152, 300), y_test: (152,)

In [11]:
model = KNeighborsClassifier()
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [12]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=6)

In [13]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=6)
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)

In [14]:
print("with scaffold splitting")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

with scaffold splitting
              precision    recall  f1-score   support

          AA       0.44      0.80      0.57        35
          AI       0.77      0.69      0.73        39
          IA       0.36      0.36      0.36        11
          II       0.88      0.55      0.68        67

    accuracy                           0.63       152
   macro avg       0.61      0.60      0.58       152
weighted avg       0.71      0.63      0.64       152

[[28  2  4  1]
 [10 27  1  1]
 [ 4  0  4  3]
 [22  6  2 37]]
0.7725937692788055
0.5088851958302126

In [15]:
#External test:
df_test = pd.read_csv("test_mol2vec_300.csv")
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("knn")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

knn
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.14      0.07      0.10        27
          IA       0.22      0.50      0.31         8
          II       0.71      0.23      0.35        74

    accuracy                           0.21       111
   macro avg       0.27      0.20      0.19       111
weighted avg       0.52      0.21      0.28       111

[[ 0  0  0  2]
 [22  2  0  3]
 [ 0  2  4  2]
 [33 10 14 17]]
0.4639003973635908
0.020589944917853032

In [11]:
model = KNeighborsClassifier(weights='distance')
params = {'n_neighbors': list(range(2, 11)), 'algorithm': ['ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(weights='distance'),
             n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [12]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=7, weights='distance')

In [13]:
clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=7, weights='distance')
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)

In [14]:
print("with scaffold splitting")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

with scaffold splitting
              precision    recall  f1-score   support

          AA       0.45      0.71      0.55        35
          AI       0.76      0.72      0.74        39
          IA       0.31      0.36      0.33        11
          II       0.87      0.60      0.71        67

    accuracy                           0.64       152
   macro avg       0.60      0.60      0.58       152
weighted avg       0.70      0.64      0.65       152

[[25  3  5  2]
 [ 9 28  1  1]
 [ 4  0  4  3]
 [18  6  3 40]]
0.7772234817481617
0.5063480086242921