In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, matthews_corrcoef

In [2]:
df = pd.read_csv("ido&tdo_mol2vec_100.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-1.453280,3.135438,-5.660918,-3.033242,-7.617049,-2.716532,-7.720714,-6.865502,-3.826457,-10.098655,...,12.327754,6.312767,-3.286225,-9.455015,6.964842,-18.937403,2.750869,16.501455,-6.681480,-4.273498
1,-3.853994,6.813040,-5.372699,-10.387832,-7.475365,-7.042470,-8.528316,-9.411233,-4.238024,-7.068585,...,14.356148,6.834394,-6.223803,-8.759715,16.309746,-23.847692,5.861533,19.511469,-11.849033,-6.109491
2,-1.180174,4.254755,-4.536231,-3.562603,-7.379086,-2.324686,-7.427113,-5.083071,-4.248663,-10.196310,...,12.481528,6.821596,-3.761701,-8.469126,7.075356,-18.553902,3.375219,16.544933,-6.834486,-4.556705
3,-0.524230,4.466556,-6.165118,-4.102696,-10.611167,-1.818723,-5.979259,-5.709599,-6.038849,-13.244520,...,12.143913,7.398972,-5.778560,-13.840563,7.989666,-23.088305,-0.075834,17.757563,-11.344548,-4.462366
4,-2.448480,3.668087,-4.891652,0.175000,-3.162153,-0.902194,-5.511296,-5.637284,0.345561,-10.797401,...,9.505338,3.902331,-7.623469,-8.973467,2.909839,-16.380924,1.064918,12.309534,-5.863398,0.419550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.039092,0.848239,-3.001012,-3.508708,-9.706405,-2.770367,-4.451425,-7.632759,-1.270038,-8.030599,...,12.036806,3.439590,-6.031008,-13.486352,6.996030,-18.041094,2.354814,8.362853,-13.254911,0.908203
756,1.353009,2.167352,-1.366708,-2.364529,-9.814615,-1.395514,-4.151305,-5.806736,-2.388004,-8.079832,...,9.126462,2.641247,-6.271195,-9.573577,4.639385,-16.821928,2.525217,9.565623,-11.529164,0.066681
757,-2.602998,7.125832,-4.669659,-10.372896,-8.373899,-5.247980,-9.301612,-8.637301,-1.214552,-7.111208,...,14.875299,8.092024,-4.372728,-11.463555,16.909105,-21.494097,4.570755,16.546633,-13.254592,-6.511065
758,-2.312877,-0.113580,0.816559,-0.219393,-5.586400,-2.550617,-2.000148,-9.507885,-2.465487,-12.263936,...,10.518041,3.871650,-4.892249,-9.578062,7.791412,-19.127460,5.459632,12.098536,-5.661181,2.037486
759,-1.734595,2.714000,-6.100870,-4.617870,-6.708008,-3.416954,-7.027505,-5.663856,-5.325977,-10.546162,...,11.494627,7.137109,-3.493536,-9.470264,6.638402,-19.514500,2.496200,16.008764,-6.865590,-4.034605

In [3]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
755      II
756      II
757      IA
758      AI
759      AA

[760 rows x 1 columns]

In [4]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [5]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-1.453280,3.135438,-5.660918,-3.033242,-7.617049,-2.716532,-7.720714,-6.865502,-3.826457,-10.098655,...,12.327754,6.312767,-3.286225,-9.455015,6.964842,-18.937403,2.750869,16.501455,-6.681480,-4.273498
1,-3.853994,6.813040,-5.372699,-10.387832,-7.475365,-7.042470,-8.528316,-9.411233,-4.238024,-7.068585,...,14.356148,6.834394,-6.223803,-8.759715,16.309746,-23.847692,5.861533,19.511469,-11.849033,-6.109491
2,-1.180174,4.254755,-4.536231,-3.562603,-7.379086,-2.324686,-7.427113,-5.083071,-4.248663,-10.196310,...,12.481528,6.821596,-3.761701,-8.469126,7.075356,-18.553902,3.375219,16.544933,-6.834486,-4.556705
3,-0.524230,4.466556,-6.165118,-4.102696,-10.611167,-1.818723,-5.979259,-5.709599,-6.038849,-13.244520,...,12.143913,7.398972,-5.778560,-13.840563,7.989666,-23.088305,-0.075834,17.757563,-11.344548,-4.462366
4,-2.448480,3.668087,-4.891652,0.175000,-3.162153,-0.902194,-5.511296,-5.637284,0.345561,-10.797401,...,9.505338,3.902331,-7.623469,-8.973467,2.909839,-16.380924,1.064918,12.309534,-5.863398,0.419550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,1.039092,0.848239,-3.001012,-3.508708,-9.706405,-2.770367,-4.451425,-7.632759,-1.270038,-8.030599,...,12.036806,3.439590,-6.031008,-13.486352,6.996030,-18.041094,2.354814,8.362853,-13.254911,0.908203
756,1.353009,2.167352,-1.366708,-2.364529,-9.814615,-1.395514,-4.151305,-5.806736,-2.388004,-8.079832,...,9.126462,2.641247,-6.271195,-9.573577,4.639385,-16.821928,2.525217,9.565623,-11.529164,0.066681
757,-2.602998,7.125832,-4.669659,-10.372896,-8.373899,-5.247980,-9.301612,-8.637301,-1.214552,-7.111208,...,14.875299,8.092024,-4.372728,-11.463555,16.909105,-21.494097,4.570755,16.546633,-13.254592,-6.511065
758,-2.312877,-0.113580,0.816559,-0.219393,-5.586400,-2.550617,-2.000148,-9.507885,-2.465487,-12.263936,...,10.518041,3.871650,-4.892249,-9.578062,7.791412,-19.127460,5.459632,12.098536,-5.661181,2.037486
759,-1.734595,2.714000,-6.100870,-4.617870,-6.708008,-3.416954,-7.027505,-5.663856,-5.325977,-10.546162,...,11.494627,7.137109,-3.493536,-9.470264,6.638402,-19.514500,2.496200,16.008764,-6.865590,-4.034605

In [6]:
X_scaled = StandardScaler().fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [11]:
model = SVC()
params = {
    "C": [0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 1, 0.1, 0.01, 0.001],
    "kernel": ["rbf", "sigmoid"]
}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1, verbose=True)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'sigmoid']},
             verbose=True)

In [12]:
grid.best_estimator_

SVC(C=10, gamma='auto')

In [8]:
clf = SVC(C=10, gamma='auto', random_state=42 , probability=True)

In [9]:
clf.fit(X_train, y_train)

SVC(C=10, gamma='auto', probability=True, random_state=42)

In [10]:
y_pred = clf.predict(X_test)

In [11]:
print("mol2vec 100 svm")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, y_pred))

mol2vec 100 svm
              precision    recall  f1-score   support

          AA       0.57      0.74      0.65        42
          AI       0.80      0.71      0.75        34
          IA       0.50      0.19      0.27        16
          II       0.79      0.82      0.80        60

    accuracy                           0.70       152
   macro avg       0.67      0.61      0.62       152
weighted avg       0.70      0.70      0.69       152

[[31  5  2  4]
 [ 6 24  0  4]
 [ 8  0  3  5]
 [ 9  1  1 49]]
0.8345050798339031
0.5775051253297981

In [12]:
#External test:
df_test = pd.read_csv("test_mol2vec_100.csv")
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("svm")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

svm
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.19      0.15      0.17        27
          IA       0.00      0.00      0.00         8
          II       0.68      0.64      0.66        74

    accuracy                           0.46       111
   macro avg       0.22      0.20      0.21       111
weighted avg       0.50      0.46      0.48       111

[[ 0  0  0  2]
 [ 8  4  1 14]
 [ 0  2  0  6]
 [ 2 15 10 47]]
0.4631329287692056
-0.018578633169851293

In [18]:
model = SVC(class_weight='balanced')
params = {
    "C": [0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 1, 0.1, 0.01, 0.001],
    "kernel": ["rbf", "sigmoid"]
}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1, verbose=True)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

GridSearchCV(cv=5, estimator=SVC(class_weight='balanced'), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'sigmoid']},
             verbose=True)

In [19]:
grid.best_estimator_

SVC(C=100, class_weight='balanced', gamma=0.001)

In [13]:
clf = SVC(C=100, class_weight='balanced', gamma=0.001, random_state=42 , probability=True)

In [14]:
clf.fit(X_train, y_train)

SVC(C=100, class_weight='balanced', gamma=0.001, probability=True,
    random_state=42)

In [15]:
y_pred = clf.predict(X_test)

In [16]:
print("mol2vec 100 svm")
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, y_pred))

mol2vec 100 svm
              precision    recall  f1-score   support

          AA       0.53      0.71      0.61        42
          AI       0.87      0.76      0.81        34
          IA       0.25      0.31      0.28        16
          II       0.82      0.62      0.70        60

    accuracy                           0.64       152
   macro avg       0.62      0.60      0.60       152
weighted avg       0.69      0.64      0.66       152

[[30  4  6  2]
 [ 5 26  0  3]
 [ 8  0  5  3]
 [14  0  9 37]]
0.8452990892189092
0.5150745577986456

In [17]:
#External test:
df_test = pd.read_csv("test_mol2vec_100.csv")
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
X_t_scaled = StandardScaler().fit_transform(X_t)
yt_pred = clf.predict(X_t_scaled)
print("svm")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t_scaled) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

svm
              precision    recall  f1-score   support

          AA       0.06      0.50      0.11         2
          AI       0.27      0.15      0.19        27
          IA       0.00      0.00      0.00         8
          II       0.70      0.45      0.55        74

    accuracy                           0.34       111
   macro avg       0.26      0.27      0.21       111
weighted avg       0.53      0.34      0.41       111

[[ 1  0  0  1]
 [11  4  7  5]
 [ 0  0  0  8]
 [ 5 11 25 33]]
0.5090236938764399
0.0062490627108847795

# **For Bemis-Murcko scaffold-splitting, run the following cells:**

In [7]:
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

In [8]:
df_total = pd.read_csv('final_total.csv')
smiles_list = [df_total.loc[i, 'smiles'] for i in range(len(df_total))]

In [9]:
def generate_scaffold(smiles, include_chirality=False):
    """
    Generate the Bemis-Murcko scaffold for a given SMILES string.
    
    Parameters:
    -----------
    smiles : str
        SMILES representation of the molecule
    include_chirality : bool
        Whether to include chirality in the scaffold
    
    Returns:
    --------
    str : Scaffold SMILES string
    """
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return smiles
        scaffold = MurckoScaffold.MurckoScaffoldSmiles(
            mol=mol, 
            includeChirality=include_chirality
        )
        return scaffold
    except:
        return smiles

def scaffold_split(X, y, smiles_list, frac_train=0.8, frac_test=0.2, seed=None):
    """
    Split data by Bemis-Murcko scaffolds.
    
    Parameters:
    -----------
    X : array-like
        Feature matrix (fingerprints)
    y : array-like
        Target labels
    smiles_list : list
        List of SMILES strings for each molecule
    frac_train : float
        Fraction of data for training
    frac_test : float
        Fraction of data for test
    seed : int or None
        Random seed for reproducibility
    
    Returns:
    --------
    tuple : (X_train, X_test, y_train, y_test, 
             idx_train, idx_test)
    """
    n_samples = len(smiles_list)
    
    # Group molecules by scaffold
    scaffolds = defaultdict(list)
    for idx, smiles in enumerate(smiles_list):
        scaffold = generate_scaffold(smiles, include_chirality=True)
        scaffolds[scaffold].append(idx)
    
    # Sort scaffolds by size (largest first)
    sorted_scaffolds = sorted(
        scaffolds.items(), 
        key=lambda x: len(x[1]), 
        reverse=True
    )
    
    # Calculate target sizes
    train_cutoff = int(frac_train * n_samples)
    
    train_idx = []
    test_idx = []
    
    # Assign entire scaffold groups to splits
    for scaffold, indices in sorted_scaffolds:
        if len(train_idx) + len(indices) <= train_cutoff:
            train_idx.extend(indices)
        else:
            test_idx.extend(indices)
    
    # Convert to numpy arrays if needed
    X = np.array(X)
    y = np.array(y)
    
    # Create splits
    X_train = X[train_idx]
    X_test = X[test_idx]
    
    y_train = y[train_idx]
    y_test = y[test_idx]
    
    print(f"Scaffold split results:")
    print(f"  Training:   {len(train_idx)} molecules ({len(train_idx)/n_samples*100:.1f}%)")
    print(f"  Test:       {len(test_idx)} molecules ({len(test_idx)/n_samples*100:.1f}%)")
    print(f"  Unique scaffolds: {len(scaffolds)}")
    
    return (X_train, X_test, 
            y_train, y_test,
            train_idx, test_idx)

In [10]:
# Perform scaffold split
X_train, X_test, y_train, y_test, idx_train, idx_test = scaffold_split(
    X_scaled, 
    y, 
    smiles_list,
    frac_train=0.8,
    frac_test=0.2,
    seed=42
)

print(f"\nShape of splits:")
print(f"  X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"  X_test: {X_test.shape}, y_test: {y_test.shape}")

Scaffold split results:
  Training:   608 molecules (80.0%)
  Test:       152 molecules (20.0%)
  Unique scaffolds: 250

Shape of splits:
  X_train: (608, 100), y_train: (608,)
  X_test: (152, 100), y_test: (152,)

In [12]:
model = SVC()
params = {
    "C": [0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 1, 0.1, 0.01, 0.001]
}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1, verbose=True)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001]},
             verbose=True)

In [13]:
grid.best_estimator_

SVC(C=1, gamma=0.001)

In [14]:
clf = SVC(probability=True, C=1, gamma=0.001, random_state=42)
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)

In [15]:
print("svm mol2vec")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
print(roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovr'))
print(matthews_corrcoef(y_test, ypred))

svm mol2vec
              precision    recall  f1-score   support

          AA       0.47      0.80      0.60        35
          AI       0.90      0.69      0.78        39
          IA       0.00      0.00      0.00        11
          II       0.75      0.70      0.72        67

    accuracy                           0.67       152
   macro avg       0.53      0.55      0.53       152
weighted avg       0.67      0.67      0.66       152

[[28  1  0  6]
 [ 8 27  0  4]
 [ 5  0  0  6]
 [18  2  0 47]]
0.8189524592290299
0.5279835297517389

In [16]:
#External test:
df_test = pd.read_csv("test_mol2vec_100.csv")
df_test_class = pd.read_csv("testdata_target.csv")
y_t = df_test_class.iloc[:,-1]
X_t = df_test.iloc[:, :]
yt_pred = clf.predict(X_t)
print("svm")
print(classification_report(y_t , yt_pred))
print(confusion_matrix(y_t , yt_pred))
print(roc_auc_score(y_t, clf.predict_proba(X_t) , multi_class='ovr'))
print(matthews_corrcoef(y_t, yt_pred))

svm
              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         2
          AI       0.00      0.00      0.00        27
          IA       0.00      0.00      0.00         8
          II       0.67      1.00      0.80        74

    accuracy                           0.67       111
   macro avg       0.17      0.25      0.20       111
weighted avg       0.44      0.67      0.53       111

[[ 0  0  0  2]
 [ 0  0  0 27]
 [ 0  0  0  8]
 [ 0  0  0 74]]
0.7224547634608703
0.0